#+TITLE: DOli flask app

this version of DOliberto uses HTML as its main format. its
architecture is heavily inspired by that of [[https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial][Grinberg's flask tutorial]].

* set-up
  you need python >3.5 and =virtualenv= installed.
  : $ virtualenv venv
  will create a virtual environment at the current directory.

  if you haven't done it yet, install the project's dependencies:
  : $ pip install -r requirements.txt

* build
  to activate the virtual environment, do
  : $ source venv/bin/activate
  and you'll be inside the virtual environment.

  to quit the virtual environment, just do
  : $ deactivate

* usage
  : $ flask shell
  will run a python shell with the flask app already setup (everything
  imported, variables set, etc.)
  : $ flask run
  will run the flask app on localhost. this requires setting the
  =FLASK_APP= variable with
  : $ export FLASK_APP=doli.py
  and (if you haven't done it before on your computer) starting the
  app's database with
  : flask db init
  if your database shema is out-of-date, run:
  : flask db upgrade
  setting flask on debug mode is also useful:
  : $ export FLASK_DEBUG=1
