"""add entities to users table

Revision ID: 8420f0d5b200
Revises: af70d494cdaa
Create Date: 2018-01-31 15:48:51.407492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8420f0d5b200'
down_revision = 'af70d494cdaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('entity', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('subentity', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_entity'), 'user', ['entity'], unique=False)
    op.create_index(op.f('ix_user_subentity'), 'user', ['subentity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subentity'), table_name='user')
    op.drop_index(op.f('ix_user_entity'), table_name='user')
    op.drop_column('user', 'subentity')
    op.drop_column('user', 'entity')
    # ### end Alembic commands ###
